language: ruby
sudo: false
cache: bundler
after_success:
  - coveralls
rvm:
    - 2.5.1
    - 2.4.0
    - ruby-head
    - jruby-1.7.26
    - jruby-9.1.7.0
    - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
